apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    environment: prod
spec:
  description: Infrastructure project for managing cluster infrastructure components
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  
  # Cluster-scoped resources needed for infrastructure components
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'networking.k8s.io'
      kind: IngressClass
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    # Prometheus monitoring cluster resources
    - group: 'monitoring.coreos.com'
      kind: Prometheus
    - group: 'monitoring.coreos.com'
      kind: Alertmanager
    - group: 'monitoring.coreos.com'
      kind: ThanosRuler
    # Kong cluster resources
    - group: 'konghq.com'
      kind: KongClusterPlugin

  # Namespace-scoped resources for infrastructure components
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget
    # Prometheus monitoring resources
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
    - group: 'monitoring.coreos.com'
      kind: PodMonitor
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule
    # Kong namespace resources
    - group: 'konghq.com'
      kind: KongPlugin
    - group: 'konghq.com'
      kind: KongIngress
    - group: 'konghq.com'
      kind: KongCredential
    - group: 'konghq.com'
      kind: KongConsumer
    - group: 'konghq.com'
      kind: KongConsumerGroup
