apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
   - matrix:
      generators:
      # git generator, 'child' #1
      - git:
          repoURL: https://github.com/huytz/gitops.git
          revision: HEAD
          directories:
          - path: apps/*/*/*
      # cluster generator, 'child' #2
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              kubernetes.io/environment: prod
  
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        appset: apps
        environment: 'prod'
        cluster: '{{.name}}'
    spec:
      project: apps      
      sources:
      - repoURL: https://helmcharts.gruntwork.io
        chart: 'k8s-service'
        targetRevision: "0.2.29"
        helm:
          valueFiles:
          - $values/{{.path.path}}/values.yaml 
      - repoURL: https://github.com/huytz/gitops.git
        targetRevision: HEAD
        ref: values

      destination:
        server: '{{.server}}'
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
