- description: Application is synced and healthy. Triggered once per commit.
  oncePer: app.status.operationState?.syncResult?.revision
  send:
    - app-deployed
  when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
    and app.status.health.status == 'Healthy' and (!time.Parse(app.status.health.lastTransitionTime).Add(1
    * time.Minute).Before(time.Parse(app.status.operationState.finishedAt)) or time.Parse(app.status.health.lastTransitionTime).Before(time.Parse(app.status.operationState.startedAt)))
