trigger.on-health-degraded: |
  - description: Application has degraded
    oncePer: app.status.operationState?.syncResult?.revision
    send:
    - app-health-degraded
    when: app.status.health.status == 'Degraded'
