trigger.on-sync-status-unknown: |
  - description: Application status is 'Unknown'
    oncePer: app.status.operationState?.syncResult?.revision
    send:
    - app-sync-status-unknown
    when: app.status.sync.status == 'Unknown'
