- description: Application syncing has succeeded
  oncePer: app.status.operationState?.syncResult?.revision
  send:
  - app-sync-succeeded
  when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
