applicationName: guestbook-ui
replicaCount: 1
containerImage:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

containerPort: 80
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

# Override the container command to source the Vault secrets
# containerCommand: ["/bin/bash", "-c"]
# containerArgs: ["source /vault/secrets/config && exec docker-php-entrypoint apache2-foreground"]

# Service Account configuration for Vault auth
serviceAccount:
  create: true
  name: guestbook-ui
  annotations:
    vault.hashicorp.com/role: "default_guestbook_ui"
  labels:
    app: guestbook-ui
    vault-auth: "true"

# Vault agent injection configuration
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/role: "default_guestbook_ui"
  vault.hashicorp.com/agent-inject-secret-config: "secrets/data/in-cluster/default/guestbook-ui"
  vault.hashicorp.com/secret-volume-path-config: "/vault/secrets"
  vault.hashicorp.com/agent-inject-template-config: |
    {{- with secret "secrets/data/in-cluster/default/guestbook-ui" -}}
    {{- range $k, $v := .Data.data -}}
    export {{ $k }}="{{ $v }}"{{ "\n" -}}
    {{- end -}}
    {{- end }}
